#是否带sandbox启动
sandbox: true

#sandbox模块选择，若设置为true就要安装依赖
modules:
  #导入需要额外安装依赖的模块
  canvas: false
  cheerio: false
  riichi: false
  syanten: false
  #导入不需要额外安装依赖的模块
  moment: true
  assert: true
  querystring: true
  path: true
  zip: true
  unzip: true
  os: true
  buffer: true
  crypto: true